# Generated by Django 2.1 on 2018-08-17 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travel_start_date', models.DateField()),
                ('travel_end_date', models.DateField()),
                ('description', models.TextField()),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_trips', to='main.User')),
                ('travelers', models.ManyToManyField(related_name='joined_trips', to='main.User')),
            ],
        ),
    ]
