# Generated by Django 2.1 on 2018-08-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='travelers',
        ),
    ]
