# Generated by Django 2.1 on 2018-08-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_trip_travelers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='planner',
        ),
    ]
