# Generated by Django 2.1 on 2018-08-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_trip_planner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='planned_trips', to='main.User'),
            preserve_default=False,
        ),
    ]
