# Generated by Django 2.1 on 2018-08-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_trip_travelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_trips', to='main.User'),
        ),
    ]
